### ISSUE TITLE
Workshop Description Translation

### ISSUE THREAD

**Issue by craftersmine** [user19990313/RimWorld-RuntimeGC#6]
Quote: "(Optional) Translate workshop description texts. Recommended; or other players using the same language will see English description texts instead."

How I can do this? Through About.xml or on Steam Workshop mod page?

Thanks

**Comment by user19990313** [comment]
Translate this file; this is the workshop description.

https://github.com/user19990313/RimWorld-RuntimeGC/blob/master/RuntimeGC.SteamWorkshopDescription.1.0.txt

Once translated, it will be used as the description of your target language on Steam workshop.
Do not translate tags like [u][/b] and create a new file for this translation.

**Comment by craftersmine** [comment]
Can I ask you?

That's is an idiom or what "You know, Too expensive to buy"? We no have that alternate expression in Russia

Thanks!

**Comment by user19990313** [comment]
That line is actually a joke: we use PS to list some tips, and the 4th tip is numbered PS4, which is also the name of Sony's console. So it's just a pun; you can safely remove it if you find it hard to get the point.

**Comment by craftersmine** [comment]
Oh, okay, thanks, then I translate as English translation
